""" securite_root/annuaire_service/annuaire_service/settings.py
Django settings for annuaire_service project.

Generated by 'django-admin startproject' using Django 2.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .routers import AnnuaireRouter
# annuaire_service/settings.py
DATABASE_ROUTERS = ['annuaire_service.routers.AnnuaireRouter']

ROOT_URLCONF = 'annuaire_service.urls'

WSGI_APPLICATION = 'annuaire_service.wsgi.application'

ANNUAIRE_SERVICE_DATABASES = {
    'annuaire_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'annuaire_db',  # Utilisez le nom de votre base de données
        'USER': 'root',
        'PASSWORD': 'shyrin12',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'unix_socket': '/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock',
        },
    }
}