version: '3'
services:
  custom_auth_service:
    build:
      context: ./custom_auth_service
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8002"
    depends_on:
      - auth_db
    volumes:
      - ./securite_projet/custom_auth_service/auth_db/templates:/app/auth_db/templates
      - ./securite_projet/custom_auth_service/auth_db/static:/app/auth_db/static

  annuaire_service:
    build:
      context: ./annuaire_service
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      - annuaire_db
    volumes:
      - ./securite_projet/annuaire_service/annuaire_db/templates:/app/annuaire_db/templates
      - ./securite_projet/annuaire_service/annuaire_db/static:/app/annuaire_db/static

  auth_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: shyrin12
      MYSQL_DATABASE: auth_db

  annuaire_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: shyrin12
      MYSQL_DATABASE: annuaire_db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - custom_auth_service
      - annuaire_service
